### ISSUE TITLE
Not working on catalog search

### ISSUE THREAD

**Issue by quienti** [czone-tech/magento2-ajaxified-catalog#1]
Hi,

I have this message all time : `Sorry, something went wrong. Please try again later.`

**Comment by ashish-czone** [comment]
Which magento version did you check this on? We tested it with 2.0.9 and 2.1.1 in Blank and Luma themes. Works fine.
Can you post a screenshot?

**Comment by quienti** [comment]
I use Magento 2.1.1, but probably this is my fault, I have some custom module...
But, I do not understand, there are not any error, just a ajax fail, no error when I get ajax error...

**Comment by quienti** [comment]
Your module works fine with catalog search ?

**Comment by ashish-czone** [comment]
Yes, it works fine with catalog search. However, are you using a custom theme? If you are using a custom theme, then there may be an issue.
If you can post a screenshot of what you see, it might help us resolve this sooner.

**Comment by quienti** [comment]
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/19070091/f66a1598-8a29-11e6-8eca-5cb6a42297d3.jpg)

No custom theme at this moment, just a lot of custom module what I created.
I have edit your module to add a translation where this error said => `Sorry, something went wrong. Please try again later.`
And I add the ability to filter with price slider (work fine when I am not in catalog search)
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/19070377/3ee56e5c-8a2b-11e6-8234-b2e6d3acfaea.jpg)

But, if you say this is works fine in catalog search, so this is my fault... But I have not error in my log or anything else

**Comment by ashish-czone** [comment]
Did you disable 'Catalog Search' module? We tested the module with the default magento installation (it has catalog search module enabled by default). 
The error that you mentioned has occurred because AJAX request failed. Please note that the AJAX request is expecting a JSON response, and it seems that in your case it is not getting a JSON response, or is getting a server side error (may be 500).
Please open the network tab and see the result of the AJAX request that was fired. Did the request ever got complete? And if it did, what was the response sent from the server? Was it valid JSON?

**Comment by quienti** [comment]
No, I have not disabled 'Catalog Search' module because my problem is on 'Catalog Search'.

Ajax works fine, not error but I not receive JSON data, I receive HTML data, my result page , that is why this is not working.

This is very strange

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/19118247/2840998c-8b1c-11e6-9880-bca39de6fb06.jpg)

**Comment by ashish-czone** [comment]
Thanks for the details, we have understood the issue and will fix it in the next update. We have the weekend off, so this will be fixed by Monday.

**Comment by bcdhamecha** [comment]
Hi,

Your module is working fine in catalog search for navigation Toolbar and in pagination. but when i do Advance search and get results the pagination didn't work it gives me message that Sorry, something went wrong. Please try again later. Can you please resolve this.

Thanks,
