### ISSUE TITLE
Add to cart not working with ajax after loading product list from ajax

### ISSUE THREAD

**Issue by sumitgithub** [czone-tech/magento2-ajaxified-catalog#2]
however this plugin didn't worked for me but I got the concept of you and implemented myself it worked but add to cart button is no more ajaxified.
Kindly help

**Comment by ashish-czone** [comment]
Please note that this interface is only for issues related to the module itself. We cannot provide support in relation to what you are asking for.
However, if you would like us to install the module in your site (we will ensure that it works), we can do that, however, installation will be chargeable. Also, if you have a custom theme/module installed, it may require extra man hours to modify the module for your particular scenario.
You may contact us regarding it at support@czonetechnologies.com, Thanks.
