### ISSUE TITLE
Not Working in Advanced Search Pagination

### ISSUE THREAD

**Issue by bcdhamecha** [czone-tech/magento2-ajaxified-catalog#3]
Hi,

Your module is working fine in catalog search for navigation Toolbar and in pagination. but when i do Advance search and get results the pagination didn't work it gives me message that 'Sorry, something went wrong. Please try again later'. I am using Magento 2.0.7 Enterprise Edition. Can you please resolve this.

Thanks,

**Comment by ashish-czone** [comment]
Thanks for your feedback. Our offices are closed until Wednesday (due to Diwali holidays in India). We will resolve this issue as soon our engineers are back at work.
